// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GTx2fM1Seq0sHuepbEVHbeqFDTTTklc',
    appId: '1:139212990091:web:12a58d98ad1a2005bc968e',
    messagingSenderId: '139212990091',
    projectId: 'stocktrend-e51d2',
    authDomain: 'stocktrend-e51d2.firebaseapp.com',
    storageBucket: 'stocktrend-e51d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OJ5_N-e-ZdJHm6Z6WtbdeM64Wjk0vQI',
    appId: '1:139212990091:android:1568d702f2349695bc968e',
    messagingSenderId: '139212990091',
    projectId: 'stocktrend-e51d2',
    storageBucket: 'stocktrend-e51d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3lG1k8nguRuqTMpy3pKYBlmfHVgzh2nU',
    appId: '1:139212990091:ios:ba66b8878b8aa66abc968e',
    messagingSenderId: '139212990091',
    projectId: 'stocktrend-e51d2',
    storageBucket: 'stocktrend-e51d2.firebasestorage.app',
    iosBundleId: 'com.example.assestTracking',
  );
}
